### ISSUE TITLE
Unable to run tests, "Jest encountered an unexpected token"

### ISSUE THREAD

**Issue by jyurek** [zo0r/react-native-push-notification#1112]
## Summary

I'm trying to create an npm module that uses `react-native-push-notification` as a dependency and is coded in TypeScript. Whe I do not reference this module, the tests run successfully. When I do reference this module, I get the error below. This error was generated with as barebones a project as I could manage.

## `npm test ` output
```
 FAIL  src/__tests__/foo.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/jyurek/Development/zrns/node_modules/react-native-push-notification/index.js:32
    Notifications.callNative = function(name: String, params: Array) {
                                            ^

    SyntaxError: Unexpected token :

    > 1 | import PushNotification from 'react-native-push-notification'
        | ^
      2 |
      3 | describe('a test', () => {
      4 |   it('create a new hello', () => {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (src/__tests__/foo.spec.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.184s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

## package.json
```
{
  "name": "zrns",
  "version": "0.0.1",
  "description": "Blah",
  "main": "dist/index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "jest"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react-native-push-notification": "^3.1.3"
  },
  "devDependencies": {
    "@types/jest": "^24.0.15",
    "@types/react-native-push-notification": "^3.0.5",
    "jest": "^24.8.0",
    "ts-jest": "^24.0.2",
    "typescript": "^3.5.2"
  },
  "jest": {
    "preset": "ts-jest",
    "testEnvironment": "node"
  }
}
```

**Comment by jyurek** [comment]
The error is almst certainly related to the fast that there seems to be TypeScript-style type declarations in functions in the `index.js` file ( [example](https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L32) ). Weirdly, a fresh react-native app with this module installed does not exhibit errors, but writing my own module and including it does cause the error.
