### ISSUE TITLE
react-native link no package found

### ISSUE THREAD

**Issue by joshuakoh7** [zo0r/react-native-push-notification#1179]
RN 0.59.3

_**react-native link react-native-push-notification**_
```
error No package found. Are you sure this is a React Native project?
error Invalid attribute name
Line: 50
Column: 16
Char: .. Run CLI with --verbose flag for more details.
```
**_react-native link react-native-push-notification --verbose_**
```
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
error No package found. Are you sure this is a React Native project?
error Invalid attribute name
Line: 50
Column: 16
Char: .
debug Error: Invalid attribute name
Line: 50
Column: 16
Char: .
    at error (*\frontendc\node_modules\xmldoc\node_modules\sax\lib\sax.js:666:10)
    at strictFail (*\frontendc\node_modules\xmldoc\node_modules\sax\lib\sax.js:692:7)
    at SAXParser.write (*\frontendc\node_modules\xmldoc\node_modules\sax\lib\sax.js:1324:13)
    at new XmlDocument (*\frontendc\node_modules\xmldoc\lib\xmldoc.js:199:15)
    at readManifest (*\frontendc\node_modules\@react-native-community\cli\build\tools\android\readManifest.js:44:10)
    at Object.projectConfig (*\frontendc\node_modules\@react-native-community\cli\build\tools\android\index.js:66:46)
    at *\frontendc\node_modules\@react-native-community\cli\build\commands\link\getProjectConfig.js:25:62
    at Array.forEach (<anonymous>)
    at getProjectConfig (*\frontendc\node_modules\@react-native-community\cli\build\commands\link\getProjectConfig.js:22:35)
    at Object.link [as func] (*\frontendc\node_modules\@react-native-community\cli\build\commands\link\link.js:74:45)
```

**Comment by Dallas62** [comment]
Hi @joshuakoh7 
You should be able to use Autolinking,
Thanks
