### ISSUE TITLE
App Crashing while receiving notification

### ISSUE THREAD

**Issue by godwin12345** [zo0r/react-native-push-notification#1213]
My app getting crash when receiving push notification through GCM, Local push notification is fine. Any Idea?

**Comment by ramosalx1504** [comment]
The same problem here on Android, using the react-native-push-notification configuration to use local notifications, since if I configure only for FCM it never notifies me of the deviceToken.

`adb logcat`

`V RNPushNotification: onMessageReceived: Bundle[{google.delivered_priority=high, google.sent_time=1571186380513, google.ttl=2419200, google.original_priority=high, body=Body of Your Notification in Data, key_1=Value for key_1, key_2=Value for key_2, title=Title of Your Notification in Title, google.message_id=0:1571186380532533%62c36fc562c36fc5, notification=Bundle[{body=UP, title=UP}], collapse_key=com.testing.rn}]

V RNPushNotification: sendNotification: Bundle[{google.delivered_priority=high, google.sent_time=1571186380513, google.ttl=2419200, google.original_priority=high, userInteraction=false, id=1118618379, body=Body of Your Notification in Data, key_1=Value for key_1, key_2=Value for key_2, title=Title of Your Notification in Title, google.message_id=0:1571186380532533%62c36fc562c36fc5, notification=Bundle[{body=UP, title=UP}], collapse_key=com.testing.rn, foreground=true}]

E AndroidRuntime: FATAL EXCEPTION: Firebase-FirebaseMessagingService

E AndroidRuntime: Process: com.testing.rn, PID: 23756

E AndroidRuntime: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.testing.rn. Make sure to call FirebaseApp.initializeApp(Context) first.

E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.0.0:180)

E AndroidRuntime: 	at com.google.firebase.messaging.MessagingAnalytics.zza(com.google.firebase:firebase-messaging@@20.0.0:75)

E AndroidRuntime: 	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(com.google.firebase:firebase-messaging@@20.0.0:2)

E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:50)

E AndroidRuntime: 	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2)

E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

E AndroidRuntime: 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)

E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

E AndroidRuntime: FATAL EXCEPTION: Firebase-FirebaseMessagingService

E AndroidRuntime: Process: com.testing.rn, PID: 23897

E AndroidRuntime: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.testing.rn. Make sure to call FirebaseApp.initializeApp(Context) first.

E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.0.0:180)

E AndroidRuntime: 	at com.google.firebase.messaging.MessagingAnalytics.zza(com.google.firebase:firebase-messaging@@20.0.0:75)

E AndroidRuntime: 	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(com.google.firebase:firebase-messaging@@20.0.0:2)

E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:50)

E AndroidRuntime: 	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2)

E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

E AndroidRuntime: 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)

E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

D OSTracker: OS Event: crash

W ActivityManager:   Force finishing activity com.testing.rn/.MainActivity`

`ENV`

Node: 8.16.0 
Yarn: 1.19.1 
npm: 6.4.1 
Watchman: 4.9.0 

react: 16.9.0 => 16.9.0
react-native: 0.61.2 => 0.61.2

Android OS Android 9 (api 28)

**Comment by godwin12345** [comment]
I'm getting this adb Log,

2019-10-16 08:39:35.712 32628-32628/com.drmanar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.drmanar, PID: 32628
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzs;
        at com.google.android.gms.gcm.GcmReceiver.onReceive(Unknown Source:78)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3379)
        at android.app.ActivityThread.access$1200(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzs" on path: DexPathList[[zip file "/data/app/com.drmanar-jUAyhbX9lxzy2PrXCOgY1Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.drmanar-jUAyhbX9lxzy2PrXCOgY1Q==/lib/x86, /data/app/com.drmanar-jUAyhbX9lxzy2PrXCOgY1Q==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.gcm.GcmReceiver.onReceive(Unknown Source:78) 
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3379) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by godwin12345** [comment]
I fixed it by removing the below from manifest file,

<receiver
     android:name="com.google.android.gms.gcm.GcmReceiver"
     android:exported="true"
     android:permission="com.google.android.c2dm.permission.SEND">
     <intent-filter>
         <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
         <category android:name="com.gnirt69.gcmexample"/>
     </intent-filter>
 </receiver>

**Comment by Kamill90** [comment]
@godwin12345 Thanks for sharing this. You saved my second half of the day of struggle.
