### ISSUE TITLE
Android crush on receive notification

### ISSUE THREAD

**Issue by tsepen** [zo0r/react-native-push-notification#1262]
This bug only in release version apk.
What is it?

Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
<unknown>@393:133
v@2:1474
<unknown>@385:685
v@2:1474
<unknown>@384:241
v@2:1474
<unknown>@383:313
v@2:1474
<unknown>@7:69
v@2:1474
<unknown>@6:30
v@2:1474
d@2:876
global code@1224:4

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:764)

**Comment by SaundersB** [comment]
Crash*
