### ISSUE TITLE
Additional FirebaseMessagingService

### ISSUE THREAD

**Issue by ewindso** [zo0r/react-native-push-notification#1356]
I need to have a primary FirebaseMessagingService in my Android app, but at the same time pass it along to react-native-push-notification.  I'm following the instructions here: https://medium.com/@chornenkyy.v/do-you-want-to-use-two-or-more-firebasemessagingservices-at-once-67236d1bd9e0

However, when I attempt to call `rnPushService.onMessageReceived(remoteMessage)`, I get: 

```
java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.react.ReactNativeHost com.facebook.react.ReactApplication.getReactNativeHost()' on a null object reference
  at com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService$1.run(RNPushNotificationListenerService.java:82)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
```

Any tips on getting past this would be great!  

Note, that if I use RNPushNotificationListenerService as my primary one, it does work properly.  

Thanks, 

Elijah

**Comment by twelvearrays** [comment]
I am having the same issue.  Did you ever solve this? THanks!

**Comment by Dallas62** [comment]
Hi @twelvearrays 
This is an old version, can you provide the stacktrace ?
The file mentioned has 67 lines when the error is on line 82.

**Comment by james-relyea** [comment]
Also encountered this issue - opened a PR with an update we're using as a workaround. Allows specifying a parent/delegate FirebaseMessagingService when instantiating `RNPushNotificationListenerService`.

**Comment by nero2009** [comment]
Hi @james-relyea I am having this same issue how were you able to fix it
