### ISSUE TITLE
conflict with react-native-onesignal, react-native-code-push and firebase, FirebaseInstanceId: Failed to get FIS auth token

### ISSUE THREAD

**Issue by omarDtp** [zo0r/react-native-push-notification#1458]
my application supports remote push notification and local schedule notification therefore i installed both libraries react-native-onesignal and react-native-push-notification.
it was working fine till lately i got this error on android devices

2020-05-27 16:51:16.628 27376-27663/xx.xxx.xxxxx E/FirebaseInstanceId: Failed to get FIS auth token 2020-05-27 16:51:16.639 27376-27376/xx.xxx.xxxxx E/RNPushNotification: exception java.io.IOException: SERVICE_NOT_AVAILABLE at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.2.0:16) at com.google.android.gms.tasks.zzd.run(Unknown Source:5) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6) at java.lang.Thread.run(Thread.java:764) 2020-05-27 16:51:16.639 27376-27376/xx.xxx.xxxxx E/RNPushNotification: exception java.io.IOException: SERVICE_NOT_AVAILABLE at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.2.0:16) at com.google.android.gms.tasks.zzd.run(Unknown Source:5) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6) at java.lang.Thread.run(Thread.java:764) 2020-05-27 16:52:31.196 27376-27764/xx.xxx.xxxxx E/FirebaseInstanceId: Failed to get FIS auth token

(your description here)

Environment
environment
"@react-native-firebase/app": "^7.1.0",
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-onesignal": "^3.7.3",
"react-native-push-notification": "^3.5.2",

**Comment by Dallas62** [comment]
Hum, not sure this issue is related to the Library.
Maybe a wrong configuration in Firebase or in dependencies:
https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase
