### ISSUE TITLE
Android API 18 Get Token not working

### ISSUE THREAD

**Issue by mromid** [zo0r/react-native-push-notification#1498]
hi
i install this package step by step and whitout problem
when i test in newer android belike 9 every thing is ok , token generate and push notif from firebase for test 

in older device with android more than 16 and lower 22 (in my case 18) token not working without any error :|

please help me :(

In addition :‌ i try with sample code on package

**Comment by Dallas62** [comment]
Hi @mromid 
I was able to reproduce what you describe. But the problem is that the notification doesn't seems to reach the phone.
I tried to found information on internet but without success.

On the documentation of Firebase, they says that we need an Emulator with GooglePlay, but there is no image like that (Google APIs only). Not sure this is  the problem because recent API are working with Google API's images.

In a last try writing this comment, I found an images with API 16 which is working:
<img width="1568" alt="Capture d’écran 2020-07-03 à 23 20 56" src="https://user-images.githubusercontent.com/3429329/86497956-f5c64a80-bd83-11ea-956e-7337a55d4ff3.png">

On this last images, everything seems to work. Good like to find working images 😄 

PS: For those who want to run the example project, Flipper need to be removed.

**Comment by Dallas62** [comment]
The tested images is on the ScreenShot.

**Comment by mromid** [comment]
thank you alot for your support❤

i tried in own computer in home but this problem ,It didn't happen!
i think this problem from network happened

Sounds like something?
(sry for my bad english)

**Comment by mromid** [comment]
@zo0r 

`E/RNPushNotification: exception
    java.io.IOException: TIMEOUT
        at com.google.firebase.iid.zzal.run(com.google.firebase:firebase-iid@@20.2.2:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
`

![Annotation 2020-07-08 154726](https://user-images.githubusercontent.com/22810402/86912561-772a2e00-c132-11ea-8d7a-ca9a3f0662e0.png)

**Comment by Dallas62** [comment]
Hi @mromid 

Sometimes simulator is stuck with network, don't know why but after this issue the network should come back.

It's in the Firebase SDK it self, we can't interact with this... 😞
