### ISSUE TITLE
Crash at launch since 7.0.0+

### ISSUE THREAD

**Issue by Aure77** [zo0r/react-native-push-notification#1896]
# Bug

Starting from react-native-push-notification@7.0.0, my app keep crashing at launch with the following message:

```
2021-03-01 13:35:50.968 16843-16843/com.myprivateapp E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk"],nativeLibraryDirectories=[/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/lib/arm64, /data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:276)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:937)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:990)
        at android.app.LoadedApk.getResources(LoadedApk.java:1234)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7263)
        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-03-01 13:35:51.059 16843-16843/com.myprivateapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myprivateapp.hf.sg, PID: 16843
    java.lang.RuntimeException: Unable to instantiate application com.myprivateapp._components.MyApplication: java.lang.ClassNotFoundException: Didn't find class "com.myprivateapp._components.MyApplication" on path: DexPathList[[zip file "/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk"],nativeLibraryDirectories=[/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/lib/arm64, /data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1306)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7401)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7374)
        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.myprivateapp._components.MyApplication" on path: DexPathList[[zip file "/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk"],nativeLibraryDirectories=[/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/lib/arm64, /data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1298)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7401) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7374) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:301) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/ReactApplication;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 14 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.ReactApplication" on path: DexPathList[[zip file "/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk"],nativeLibraryDirectories=[/data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/lib/arm64, /data/app/~~KM-BCiN5CfAC4X8OuBkiDg==/com.myprivateapp-QWKbTBcMxkUJ1p-w9usZ5w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 17 more

```

It's work without problems with 6.1.3. There is maybe new requirement since 7.0.0+ (firebase/androidx dependencies ?) ?
I am using `com.google.firebase:firebase-bom:25.7.0` for firebase deps versions and `androidx.appcompat:appcompat:1.2.0`, supportLibVersion = "28.0.0".

## Environment info

`react-native info` output:

```bash
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
```

Library version: 7.2.1 (also tested 7.0.0)

**Comment by Dallas62** [comment]
Hi @Aure77 
Requirements didn't changed in `7.x`.
You can try to go back in the previous version and rebuild the project same issue should still occure.
Regards,

**Comment by Aure77** [comment]
My bad, you right. `Android Studio -> Clean project` was not enough. Using `./gradlew clean cleanBuildCache installDebug` make sure that cache/intermediates are rebuild...
