### ISSUE TITLE
TypeError: null is not an object (evaluating 'o.getInitialNotification')

### ISSUE THREAD

**Issue by devransimsek** [zo0r/react-native-push-notification#2013]
I had a problem after upgrade the react-native-push-notification on "v7.3.1" on Android.

there is no any problem on development mode but  when i wanted to run on release mode with;

react-native run-android --variant=release

app is crashing suddenly. i tried cache clean, remove build folder, remove node_modules and reinstall but it still not working.

How can i fix it ? 

here is crashlytics details ; 

Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'o.getInitialNotification'), stack:
getInitialNotification@479:171
popInitialNotification@478:6861
o@478:2350
configure@478:2547
<unknown>@6:154
v@2:1473
d@2:875
global code@1652:3

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)

**Comment by Dallas62** [comment]
Please search in issue history.
Regards.
