### ISSUE TITLE
Scheduling a notification causes a SecurityException on Android 12

### ISSUE THREAD

**Issue by jamesrogers93** [zo0r/react-native-push-notification#2205]
I'm getting a `SecurityException: Caller needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms` on the following line:
https://github.com/zo0r/react-native-push-notification/blob/e1a07166d5e291a5c117fdbd4b5a45472616e771/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L178

Looks to be new behaviour with API level 31 as per the docs https://developer.android.com/training/scheduling/alarms#exact 

> The system invokes an exact alarm at a precise moment in the future. If your app targets Android 12 (API level 31) or higher, you must declare the "Alarms & reminders" special app access; otherwise, a SecurityException occurs.

May need to mention somewhere in the docs to add the `<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>` in the `manifest.xml`.

As this permission can be disabled, the `canScheduleExactAlarms()` [(docs)](https://developer.android.com/reference/android/app/AlarmManager#canScheduleExactAlarms()) check looks to be needed before trying to schedule an exact alarm.

I'm happy to make a PR with the proposed changes if needed

**Comment by Dallas62** [comment]
Hi,

https://github.com/zo0r/react-native-push-notification#state-of-the-repository

Regards

**Comment by deflexable** [comment]
also having this issue on android 12. Basically happens when users try to schedule a notification

were you able to come up with a solution?

my crashlytics logs

`Fatal Exception: java.lang.SecurityException: Caller com.faithful.heavenya needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
       at android.os.Parcel.createException(Parcel.java:2409)
       at android.os.Parcel.readException(Parcel.java:2392)
       at android.os.Parcel.readException(Parcel.java:2334)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:359)
       at android.app.AlarmManager.setImpl(AlarmManager.java:947)
       at android.app.AlarmManager.setImpl(AlarmManager.java:907)
       at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:1175)
       at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotificationScheduledCore(RNPushNotificationHelper.java:66)
       at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotificationScheduled(RNPushNotificationHelper.java:128)
       at com.dieam.reactnativepushnotification.modules.RNPushNotification.scheduleLocalNotification(RNPushNotification.java:27)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:148)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:21)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:920)`

**Comment by tahir-zahid** [comment]
@jamesrogers93 did you create any PR or Fork for this solution ??

**Comment by brianlenz** [comment]
I used this patch to check `canScheduleExactAlarms()`:

```
diff --git a/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java b/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
index 248ff0825af89ce82e2c7346ef1edc104b06c91c..a228a63f1033fac9622148de79928fed90e26d95 100644
--- a/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
+++ b/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
@@ -170,6 +170,12 @@ public class RNPushNotificationHelper {
         if (pendingIntent == null) {
             return;
         }
+        
+        // call canScheduleExactAlarms to confirm the user has allowed alarms to be set. otherwise,
+        // attempting to set an alarm below will crash the app!
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && !getAlarmManager().canScheduleExactAlarms()) {
+            return;
+        }
 
         Log.d(LOG_TAG, String.format("Setting a notification with id %s at time %s",
                 bundle.getString("id"), Long.toString(fireDate)));
```

**Comment by BamMironov** [comment]
@brianlenz could you please tell me how you applied this patch?
I use patch-package and have created react-native-push-notification+8.1.1.patch with your changes.
But it fails to patch them with this error:
```
**ERROR** Failed to apply patch for package react-native-push-notification at path
  
    node_modules/react-native-push-notification

  This error was caused because patch-package cannot apply the following patch file:

    patches/react-native-push-notification+8.1.1.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package react-native-push-notification
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues
```

I tried to reinstall the package. Even removed node_modules but nothing helps

**Comment by brianlenz** [comment]
@BamMironov, we are using [yarn patch](https://yarnpkg.com/cli/patch) from Yarn 2. If you're using Yarn 1, then [patch-package](https://yarnpkg.com/package/patch-package) is the way to go. I might suggest you contact their team for further assistance, as the issue likely has nothing to do with the contents of the patch itself.
