### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference

### ISSUE THREAD

**Issue by waterflower124** [zo0r/react-native-push-notification#2207]
# Bug

## Environment info

react-native 0.63.4
android studio 4.1.2
mac ox 12.0.1

There is runtime error as follow

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
        at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.getMainActivityClass(RNPushNotificationHelper.java:67)
        at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotificationScheduled(RNPushNotificationHelper.java:119)
        at com.dieam.reactnativepushnotification.modules.RNPushNotification.scheduleLocalNotification(RNPushNotification.java:183)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:246)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)

anyone who can fix the issue?

**Comment by matrec4** [comment]
I'm having the same problem

**Comment by pivkdn** [comment]
same with me
