### ISSUE TITLE
Can't send local notifications

### ISSUE THREAD

**Issue by adambene** [zo0r/react-native-push-notification#222]
When I try to:

```
PushNotification.localNotification({
    message: 'My Notification Message',
});
```

I get:

```
10-05 22:48:01.182  3663  5425 E RNPushNotification: failed to send push notification
10-05 22:48:01.182  3663  5425 E RNPushNotification: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.getMainActivityClass(RNPushNotificationHelper.java:52)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotification(RNPushNotificationHelper.java:133)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.dieam.reactnativepushnotification.modules.RNPushNotification.presentLocalNotification(RNPushNotification.java:198)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at java.lang.reflect.Method.invoke(Native Method)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:322)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at android.os.Handler.handleCallback(Handler.java:739)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at android.os.Handler.dispatchMessage(Handler.java:95)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at android.os.Looper.loop(Looper.java:148)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
10-05 22:48:01.182  3663  5425 E RNPushNotification:    at java.lang.Thread.run(Thread.java:818)
```

Using react-native-push-notification@2.1.1

Devices:
Android 6 emulator, API 23 with GApps
Andriod 5 emulator, API 21 with GApps
Android 5 real device

Any idea?

**Comment by platonish** [comment]
@Gp2mv3 were you able to resolve this? I'm faced with the same issue 😕

**Comment by l0ger** [comment]
I'm faced with the same issue too. not any one solve this issue?
