### ISSUE TITLE
  Caused by: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast fromrequires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.

### ISSUE THREAD

**Issue by pankajnegi1893** [zo0r/react-native-push-notification#2260]
Android 12 we are getting crash when clicking on Notification. 

Please check the error log :- 

`FATAL EXCEPTION: main
    Process: in.ap.doctordhanush.uttarakandtm, PID: 10238
    java.lang.RuntimeException: Unable to start receiver com.dieam.reactnativepushnotification.modules.RNPushNotificationActions: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from in.ap.doctordhanush.uttarakandtm (pid=10238, uid=10147) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4315)
        at android.app.ActivityThread.access$1400(ActivityThread.java:250)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2056)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7829)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
     Caused by: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from in.ap.doctordhanush.uttarakandtm (pid=10238, uid=10147) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5685)
        at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1178)
        at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
        at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
        at com.dieam.reactnativepushnotification.modules.RNPushNotificationActions.onReceive(RNPushNotificationActions.java:65)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4306)
        at android.app.ActivityThread.access$1400(ActivityThread.java:250) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2056) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7829) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:2913)
        at com.android.server.wm.ActivityTaskManagerService.access$900(ActivityTaskManagerService.java:294)
        at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:5265)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13172)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12741)`

Please look into this issue.

Thanks

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#state-of-the-repository

**Comment by JayG21** [comment]
This issue is happening due to Android 12 has no permission of android.intent.action.CLOSE_SYSTEM_DIALOGS because it's deprecated in API 31

![image](https://user-images.githubusercontent.com/50162767/182075977-df22132d-cc6f-481a-a75d-d6b89b72d381.png)

I find solution for this but There is one change need to be done inside library file into RNPushNotificationActions.java

![image](https://user-images.githubusercontent.com/50162767/182075677-386d4326-49e4-4759-a9a0-0f00dc2bec6e.png)

We just need to add try catch around send broadcast
