### ISSUE TITLE
Closed Android app crashes on notification with 2.2.0

### ISSUE THREAD

**Issue by damusnet** [zo0r/react-native-push-notification#289]
With `react-native-push-notification`@2.2.0, notifications work fine on iOS and on Android with the App open. However, when a notification arrives with the App completely closed (not even running in background), you can see a flash (probably something launching in the background), and then there is a popup `"Unfortunately, <App> has stopped."`

Here is the stacktrace from Android Studio:

```
W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {3451852} sending message to a Handler on a dead thread
                java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {3451852} sending message to a Handler on a dead thread
                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                    at android.os.Handler.enqueueMessage(Handler.java:631)
                    at android.os.Handler.sendMessageAtTime(Handler.java:600)
                    at android.os.Handler.sendMessageDelayed(Handler.java:570)
                    at android.os.Handler.post(Handler.java:326)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                    at android.os.Handler.handleCallback(Handler.java:739)
                    at android.os.Handler.dispatchMessage(Handler.java:95)
                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                    at android.os.Looper.loop(Looper.java:148)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                    at java.lang.Thread.run(Thread.java:818)
```

I suspect this is related to #267 and does not happen after downgrading to 2.1.1

**Comment by jsdario** [comment]
I have the same issue with similar indetermination. All I can read is
```
W/PackageManager( 1277): Failure retrieving resources for com.netbeast.yeti.debug: Resource ID #0x0
```

**Comment by Arkanine** [comment]
Have the same issue.

**Comment by mikelambert** [comment]
Can this be closed now, with https://github.com/zo0r/react-native-push-notification/pull/269 having been committed and released in 2.2.1?

**Comment by damusnet** [comment]
Not tested but I trust it to work. Closing for now. Will reopen if necessary.
Thanks a lot for your work :)

**Comment by rizkisunaryo** [comment]
Please reopen. I'm facing the same issue.
