### ISSUE TITLE
It crashes when the app is turned off.

### ISSUE THREAD

**Issue by henrykapostel** [zo0r/react-native-push-notification#309]
Hello,

I implemented the react-native-push-notification on my project and just tested on my android device.
#1. When I installed the apk on my android device after I implemented push notification, it crashed( Please check this screenshot and let me know what the reason is
[Error Calling function: RCTDeviceEventEmitter:emit](https://cloud.githubusercontent.com/assets/12963927/21026877/dd9e0324-bd8e-11e6-8135-27eebe8bfa22.png))
#2. Also, I turned off the app and send message to my android device, the notification didn't show, but the logs were displayed  as following:
java.lang.NullPointerException
                                                                 at com.audioStreaming.ReactNativeAudioStreamingModule.getClassActivity(ReactNativeAudioStreamingModule.java:43)
                                                                 at com.audioStreaming.Signal.setData(Signal.java:76)
                                                                 at com.audioStreaming.ReactNativeAudioStreamingModule.onServiceConnected(ReactNativeAudioStreamingModule.java:82)
                                                                 at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1114)
                                                                 at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1131)
                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:146)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5653)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                 at dalvik.system.NativeStart.main(Native Method)

When the app is in background and I send notification to the app, the android device shows the push notification. I want to fix these 2 bugs asap.
Thanks

**Comment by arshavinho** [comment]
hey @henrykapostel i have the same error but i think its related to react-native-audio-streaming ?
Do you have a fix ?

''12-13 16:44:06.200  4518  4518 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at com.audioStreaming.ReactNativeAudioStreamingModule.getClassActivity(ReactNativeAudioStreamingModule.java:43)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at com.audioStreaming.Signal.setData(Signal.java:66)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at com.audioStreaming.ReactNativeAudioStreamingModule.onServiceConnected(ReactNativeAudioStreamingModule.java:78)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-13 16:44:06.200  4518  4518 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
''

**Comment by npomfret** [comment]
Hi, would you like to close this discussion?  I don't think it has anything to do with react-native-push-notification.  Thanks!

**Comment by henrykapostel** [comment]
Well.. I used other push-notification - https://github.com/evollu/react-native-fcm and it works well..
Thanks
