### ISSUE TITLE
Getting a ClassNotFoundException

### ISSUE THREAD

**Issue by nlively** [zo0r/react-native-push-notification#311]
I am getting the following error showing up a lot in Crashlytics since we launched a new app over the weekend.  The issue is not repeatable so far on my own Samsung Galaxy S5 or my co-worker's Samsung Note 5.  However, it has appeared over 100 times in Crashlytics since Saturday morning.

Versions:
- react-native: 0.36.0
- react-native-push-notification: 2.1.0

Any insights?  Thanks in advance

```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver: java.lang.ClassNotFoundException: Didn't find class "com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver" on path: DexPathList[[zip file "/data/app/com.my.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.my.app-2/lib/arm, /vendor/lib, /system/lib]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3480)
       at android.app.ActivityThread.access$1900(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1758)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6862)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.ClassNotFoundException: Didn't find class "com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver" on path: DexPathList[[zip file "/data/app/com.my.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.my.app-2/lib/arm, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3475)
       at android.app.ActivityThread.access$1900(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1758)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6862)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by nlively** [comment]
This was caused by reverting from 2.2.0 to 2.1.0 and not removing the newer code from my AndroidManifest.xml file.  Problem solved.

**Comment by eramudeep** [comment]
> 
> 
> This was caused by reverting from 2.2.0 to 2.1.0 and not removing the newer code from my AndroidManifest.xml file. Problem solved.

do you mind explaining .?
i didn`t get what you are saying to remove or replace
