### ISSUE TITLE
Hard crash on Android

### ISSUE THREAD

**Issue by mikefowler** [zo0r/react-native-push-notification#38]
**Update**: If you're seeing crashes with this library and logs point to `com.google.android.gcm`, it's possible that another project dependency is requiring a newer version of Play Services than this one. In our case, we're using [react-native-maps](https://github.com/lelandrichardson/react-native-maps), which lists `com.google.android.gms:play-services-maps:8.4.0` as a dependency. This library lists `com.google.android.gms:play-services-gcm:8.3.0`. Forking this library and updating that dependency to number `8.4.0` resolved our crash.

Implementing this library in our app results in hard crashes when building the Android app. We've double and triple checked the installation instructions and everything is as instructed. When running `react-native run-android`, the app immediately crashes with the standard `Unfortunately [App] has stopped.`.

The only (seemingly) relevant crash logs from logcat are below. Any insight into why this might be happening? No mention of this in any other issues so far.

```
W/dalvikvm(12272): threadid=1: thread exiting with uncaught exception (group=0x415f4ba8)
E/AndroidRuntime(12272): FATAL EXCEPTION: main
E/AndroidRuntime(12272): Process: com.[redacted], PID: 12272
E/AndroidRuntime(12272): java.lang.NoSuchMethodError: com.google.android.gms.common.internal.zzx.zzy
E/AndroidRuntime(12272):        at com.google.android.gms.measurement.internal.zzt.zzaU(Unknown Source)
E/AndroidRuntime(12272):        at com.google.android.gms.measurement.AppMeasurementContentProvider.onCreate(Unknown Source)
E/AndroidRuntime(12272):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime(12272):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime(12272):        at android.app.ActivityThread.installProvider(ActivityThread.java:4790)
E/AndroidRuntime(12272):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
E/AndroidRuntime(12272):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
E/AndroidRuntime(12272):        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime(12272):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(12272):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12272):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(12272):        at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime(12272):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12272):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12272):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime(12272):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime(12272):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  760):   Force finishing activity com.[redacted]/.MainActivity
```

**Comment by jedlau** [comment]
Thanks, @mikefowler . Just ran into this. Looks like this is fixed in 1.0.6: https://github.com/zo0r/react-native-push-notification/commit/77115ee3c35ec86ae512e90a56ae0df80bb0ce6e
