### ISSUE TITLE
Add information about main intent in trouble shooting

### ISSUE THREAD

**Issue by petha** [zo0r/react-native-push-notification#497]
I've struggled a couple of hours before I found out that my splash screen were returned by getMainActivityClass().

Might be a good idea to add a paragraph about it in trouble shooting?

**Comment by luandro** [comment]
Yea, this would be nice. It's hard to find out what the errors are saying:
```
06-18 08:29:23.605 13578-13663/? E/RNPushNotification: RNPushNotification failed to process intent Intent { cmp=com.apphub/com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }
    java.io.IOException: INVALID_SENDER
        at com.google.android.gms.iid.zze.zzb(Unknown Source)
        at com.google.android.gms.iid.zze.zza(Unknown Source)
        at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
        at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
        at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:25)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by luandro** [comment]
@minhphung210 Unfortunately no...

**Comment by SkyTreasure** [comment]
Any solution for this? Facing the same issue in the release build.
