### ISSUE TITLE
java.lang.NoClassDefFoundError [ANDROID]

### ISSUE THREAD

**Issue by cinder92** [zo0r/react-native-push-notification#503]
Hello, after install this plugins, i can't run my app this error occurs 

```
E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
                                                                                  at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:24)
                                                                                  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:150)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.elevmech.clubhousenow-1/base.apk"],nativeLibraryDirectories=[/data/app/com.elevmech.clubhousenow-1/lib/arm, /data/app/com.elevmech.clubhousenow-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                  at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:24) 
                                                                                  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:150) 
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                              	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
                                                                                  at java.lang.Class.classForName(Native Method)
                                                                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                  		... 6 more
                                                                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
08-04 19:38:55.860 11806-12912/com.elevmech.clubhousenow E/AndroidRuntime: FATAL EXCEPTION: IntentService[RNPushNotification]
                                                                           Process: com.elevmech.clubhousenow, PID: 11806
                                                                           java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
                                                                               at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:24)
                                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:150)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.elevmech.clubhousenow-1/base.apk"],nativeLibraryDirectories=[/data/app/com.elevmech.clubhousenow-1/lib/arm, /data/app/com.elevmech.clubhousenow-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:24) 
                                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:150) 
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                           	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                               		... 6 more
                                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
08-04 19:38:55.890 11806-12912/com.elevmech.clubhousenow I/Process: Sending signal. PID: 11806 SIG: 9
```

dependencies

```
dependencies {
    compile project(':react-native-code-push')
    compile project(':react-native-firebase')
    compile project(':react-native-image-picker')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-vector-icons')
    compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms"
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

Any ideas?

**Comment by mayankbaiswar-CSE** [comment]
Did you happen to solve this issue?

**Comment by KPS250** [comment]
Might this help you:

 implementation(project(":react-native-firebase"),  {
        exclude group: "com.google.android.gms"
        exclude group: "com.google.firebase"
    })

    implementation (project(':react-native-push-notification'), {
        exclude group: "com.google.android.gms"
        exclude group: "com.google.firebase"
    })

implementation ("com.google.android.gms:play-services-base:10.0.1") {
        force = true;
    }
    implementation ("com.google.android.gms:play-services-gcm:10.0.1") {
        force = true;
    }
    implementation ('com.google.firebase:firebase-core:10.0.1') {
        force = true;
    }
    implementation ('com.google.firebase:firebase-messaging:10.0.1') {
        force = true;
    }
