### ISSUE TITLE
App crashing on PushNotification.configure() -Android

### ISSUE THREAD

**Issue by zasyadev** [zo0r/react-native-push-notification#750]
I have configure the package as per the installation docs. 
As soon as I call `PushNotification.configure()` in componentDidMount(). The app crashes immediately.

```
PushNotification.configure({
      
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: (token) => {
        this.props.dispatch(saveDeviceToken(token));
        console.log('TOKEN:', token);
      },

      // (required) Called when a remote or local notification is opened or received
      onNotification: (notification) => {
        console.log('NOTIFICATION:', notification);
      },

      // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
      senderID: '422724865895',

      // Should the initial notification be popped automatically
      // default: true
      popInitialNotification: true,

      requestPermissions: true,
    });
```

"react-native-push-notification": "^3.0.2",
"react-native": "0.53.3",
"react": "16.2.0"

**Comment by ASteinheiser** [comment]
Same here, using:

"react": "16.2.0",
"react-native": "0.52.2",
"react-native-push-notification": "^3.0.2",

**Comment by leoabacade** [comment]
changing 

compile ('com.google.android.gms:play-services-gcm:11.6.2') {
        force = true;
    }

from 

compile ('com.google.android.gms:play-services-gcm:9.4.0') {
        force = true;
    }

solved my issue.

maker sure your google play-services dependencies at all components are at newest version.

**Comment by iamsee** [comment]
+1 
it's   requestPermissions: true   cause my app crash

**Comment by quynhnguyen68** [comment]
I also got app crashing but when receiving notification
```
FATAL EXCEPTION: main
    Process: com.online2study.mobile, PID: 31428
    android.app.RemoteServiceException: Bad notification posted from package com.online2study.mobile: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.online2study.mobile id=0x7f030001) visible user=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1775)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Rekha16** [comment]
Hi I am having same issue can any one help to resolve this issue

**Comment by gczudowski** [comment]
Same issue here. Has anyone solved it?
