### ISSUE TITLE
App restarts when notification received. onNotification not called

### ISSUE THREAD

**Issue by KthProg** [zo0r/react-native-push-notification#846]
When I start my application, one the first notification received the app goes to the root view. There don't appear to be any errors, it just navigates to the login for no reason. Subsequent notifications simply do nothing, including not calling the handler I have set up.

**Comment by KthProg** [comment]
I do get a strange message about permissions:
```
08-26 16:49:46.998 3280-3357/? W/PackageManager: Not granting permission host.exp.exponent.permission.C2D_MESSAGE to package com.eesoft.cardlife (protectionLevel=2 flags=0x3858be44)
    Unknown permission android.permission.READ_INTERNAL_STORAGE in package com.eesoft.cardlife
    Not granting permission android.permission.MANAGE_DOCUMENTS to package com.eesoft.cardlife (protectionLevel=2 flags=0x3858be44)
    Unknown permission com.sec.android.provider.badge.permission.READ in package com.eesoft.cardlife
    Unknown permission com.sec.android.provider.badge.permission.WRITE in package com.eesoft.cardlife
    Unknown permission com.htc.launcher.permission.READ_SETTINGS in package com.eesoft.cardlife
    Unknown permission com.htc.launcher.permission.UPDATE_SHORTCUT in package com.eesoft.cardlife
    Unknown permission com.sonyericsson.home.permission.BROADCAST_BADGE in package com.eesoft.cardlife
    Unknown permission com.sonymobile.home.permission.PROVIDER_INSERT_BADGE in package com.eesoft.cardlife
    Unknown permission com.anddoes.launcher.permission.UPDATE_COUNT in package com.eesoft.cardlife
    Unknown permission com.majeur.launcher.permission.UPDATE_BADGE in package com.eesoft.cardlife
    Unknown permission com.huawei.android.launcher.permission.CHANGE_BADGE in package com.eesoft.cardlife
08-26 16:49:46.999 3280-3357/? W/PackageManager: Unknown permission com.huawei.android.launcher.permission.READ_SETTINGS in package com.eesoft.cardlife
    Unknown permission com.huawei.android.launcher.permission.WRITE_SETTINGS in package com.eesoft.cardlife
```

**Comment by KthProg** [comment]
I also see things like this quite a bit: `08-26 16:57:49.933 23701 25650 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode`

**Comment by KthProg** [comment]
And I saw this but I haven't had any crashes:
```
08-26 16:57:49.623 23701 25649 W System.err: org.json.JSONException: No value for bundledAssets
08-26 16:57:49.623 23701 25649 W System.err: 	at org.json.JSONObject.get(JSONObject.java:389)
08-26 16:57:49.623 23701 25649 W System.err: 	at org.json.JSONObject.getJSONArray(JSONObject.java:584)
08-26 16:57:49.623 23701 25649 W System.err: 	at versioned.host.exp.exponent.modules.api.FileSystemModule.getBundledAssets(FileSystemModule.java:119)
08-26 16:57:49.624 23701 25649 W System.err: 	at versioned.host.exp.exponent.modules.api.FileSystemModule.getConstants(FileSystemModule.java:101)
08-26 16:57:49.624 23701 25649 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:138)
08-26 16:57:49.624 23701 25649 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-26 16:57:49.624 23701 25649 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
08-26 16:57:49.624 23701 25649 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-26 16:57:49.624 23701 25649 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
08-26 16:57:49.624 23701 25649 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-26 16:57:49.624 23701 25649 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
08-26 16:57:49.624 23701 25649 W System.err: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by KthProg** [comment]
Here's what appear to be the logs when receiving the notification:
```
08-26 16:57:47.869 23701 25605 W Bundle  : Key google.sent_time expected String but value was a java.lang.Long.  The default value <null> was returned.
08-26 16:57:47.869 23701 25605 W Bundle  : Attempt to cast generated internal exception:
08-26 16:57:47.869 23701 25605 W Bundle  : java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
08-26 16:57:47.869 23701 25605 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:995)
08-26 16:57:47.869 23701 25605 W Bundle  : 	at com.google.android.gms.gcm.b.a(Unknown Source)
08-26 16:57:47.869 23701 25605 W Bundle  : 	at com.google.android.gms.gcm.a.handleIntent(Unknown Source)
08-26 16:57:47.869 23701 25605 W Bundle  : 	at com.google.firebase.iid.c.run(Unknown Source)
08-26 16:57:47.869 23701 25605 W Bundle  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-26 16:57:47.869 23701 25605 W Bundle  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-26 16:57:47.869 23701 25605 W Bundle  : 	at java.lang.Thread.run(Thread.java:761)
08-26 16:57:47.870 23701 25605 W Bundle  : Key google.ttl expected String but value was a java.lang.Integer.  The default value <null> was returned.
08-26 16:57:47.870 23701 25605 W Bundle  : Attempt to cast generated internal exception:
08-26 16:57:47.870 23701 25605 W Bundle  : java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
08-26 16:57:47.870 23701 25605 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:995)
08-26 16:57:47.870 23701 25605 W Bundle  : 	at com.google.android.gms.gcm.b.a(Unknown Source)
08-26 16:57:47.870 23701 25605 W Bundle  : 	at com.google.android.gms.gcm.a.handleIntent(Unknown Source)
08-26 16:57:47.870 23701 25605 W Bundle  : 	at com.google.firebase.iid.c.run(Unknown Source)
08-26 16:57:47.870 23701 25605 W Bundle  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-26 16:57:47.870 23701 25605 W Bundle  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-26 16:57:47.870 23701 25605 W Bundle  : 	at java.lang.Thread.run(Thread.java:761)
08-26 16:57:47.871 23701 25605 E ExponentGcmListenerService: No experienceId in push payload.
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: Error while parsing timestamp in GCM event
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: java.lang.NumberFormatException: null
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at java.lang.Integer.parseInt(Integer.java:483)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at java.lang.Integer.valueOf(Integer.java:611)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at com.google.firebase.messaging.f.a(Unknown Source)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at com.google.firebase.messaging.f.a(Unknown Source)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at com.google.firebase.iid.c.run(Unknown Source)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-26 16:57:47.886 23701 25606 W FirebaseMessaging: 	at java.lang.Thread.run(Thread.java:761)
08-26 16:57:47.902 23701 25607 D FA      : Logging event (FE): notification_receive(_nr), Bundle[{firebase_event_origin(_o)=fcm, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: Error while parsing timestamp in GCM event
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: java.lang.NumberFormatException: null
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at java.lang.Integer.parseInt(Integer.java:483)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at java.lang.Integer.valueOf(Integer.java:611)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at com.google.firebase.messaging.f.a(Unknown Source)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at com.google.firebase.messaging.f.d(Unknown Source)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at com.google.firebase.iid.c.run(Unknown Source)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-26 16:57:47.905 23701 25606 W FirebaseMessaging: 	at java.lang.Thread.run(Thread.java:761)
08-26 16:57:47.910  3280 13017 D LocationManagerService: getProviders()=[passive, gps, network]
08-26 16:57:47.911 23701 25606 V RNPushNotification: onMessageReceived: Bundle[{userId=1, id=2, body=You have received a new trophy, data=8, type=TrophyReceived, title=Trophy Received, webSocketOnly=false}]
08-26 16:57:47.912  3280  3298 D LocationManagerService: getLastLocation: Request[POWER_NONE passive fastest=0 num=1]
08-26 16:57:47.914  3280 13011 D LocationManagerService: getLastLocation: Request[ACCURACY_FINE gps requested=0 fastest=0 num=1]
08-26 16:57:47.916  3280 22482 D LocationManagerService: getLastLocation: Request[POWER_LOW network requested=0 fastest=0 num=1]
08-26 16:57:47.916 23701 23701 D ReactNative: ReactInstanceManager.ctor()
08-26 16:57:47.918 23701 23701 D ReactNative: ReactInstanceManager.createReactContextInBackground()
08-26 16:57:47.918 23701 23701 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
08-26 16:57:47.918 23701 23701 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
08-26 16:57:47.918 23701 23701 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
08-26 16:57:47.918 23701 23701 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
08-26 16:57:47.918 23701 25607 V FA      : Using measurement service
08-26 16:57:47.920 23701 25610 D ReactNative: ReactInstanceManager.createReactContext()
08-26 16:57:47.920 23701 25607 V FA      : Connecting to remote service
08-26 16:57:47.930 23701 25610 D ReactNative: Initializing React Xplat Bridge.
08-26 16:57:47.931 23701 25607 D FA      : Logging event (FE): notification_foreground(_nf), Bundle[{firebase_event_origin(_o)=fcm, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]
08-26 16:57:47.933 23701 25610 D ReactNative: Initializing React Xplat Bridge before initializeBridge
08-26 16:57:47.943 23701 25607 V FA      : Using measurement service
08-26 16:57:47.943 23701 25607 V FA      : Connection attempt already in progress
08-26 16:57:47.943 23701 25607 D FA      : Connected to remote service
08-26 16:57:47.943 23701 25607 V FA      : Processing queued up service tasks: 2
08-26 16:57:47.950 23701 25610 D ReactNative: Initializing React Xplat Bridge after initializeBridge
08-26 16:57:47.950 23701 25610 D ReactNative: CatalystInstanceImpl.runJSBundle()
08-26 16:57:47.961 21081 25614 V FA-SVC  : Logging event: origin=fcm,name=notification_receive(_nr),params=Bundle[{firebase_event_origin(_o)=fcm, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]
08-26 16:57:47.973  3280  4173 D InputDispatcher: Focus left window: Window{8a05966 u0 com.eesoft.cardlife/host.exp.exponent.MainActivity}
08-26 16:57:47.975  3280  4173 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
08-26 16:57:48.002 23701 23701 I Timeline: Timeline: Activity_launch_request id:com.eesoft.cardlife time:1080225833
08-26 16:57:48.005  3280 13014 I ActivityManager: START u0 {flg=0xc080000 cmp=com.eesoft.cardlife/host.exp.exponent.MainActivity} from uid 10291 on display 0
08-26 16:57:48.007 21081 25614 V FA-SVC  : Saving event, name, data size: notification_receive(_nr), 52
08-26 16:57:48.008 21081 25614 V FA-SVC  : Event recorded: Event{appId='com.eesoft.cardlife', name='notification_receive(_nr)', params=Bundle[{firebase_event_origin(_o)=fcm, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]}
08-26 16:57:48.011 21081 25614 V FA-SVC  : Upload scheduled in approximately ms: 3141687
08-26 16:57:48.013  3280 13014 E asset   : AssetManager::addSystemOverlays delete oidmap
08-26 16:57:48.018  3280 13014 V OverlayManager: getOverlayInfosForTarget for user#0
08-26 16:57:48.019  3280 13014 I ActivityManager: Ignoring FLAG_ACTIVITY_NEW_DOCUMENT, launchMode is "singleInstance" or "singleTask"
08-26 16:57:48.021  3280 13014 D ActivityManager: setTaskToReturnTo : TaskRecord{32896a #2457 A=com.eesoft.cardlife U=0 StackId=1 sz=0} / mTaskToReturnTo = 0
08-26 16:57:48.021  3280 13014 D ActivityManager: setTaskToReturnTo : TaskRecord{32896a #2457 A=com.eesoft.cardlife U=0 StackId=1 sz=0} / mTaskToReturnTo = 1
08-26 16:57:48.024  8682  8693 D PenService: [activityStarting]
08-26 16:57:48.025  3280 13014 D ActivityManager: setTaskToReturnTo : TaskRecord{32896a #2457 A=com.eesoft.cardlife U=0 StackId=1 sz=1} / mTaskToReturnTo = 1
08-26 16:57:48.035  3280  3348 I WindowManager: Do not prepare transition because this AppWindow will be hidden.
08-26 16:57:48.036 21081 25614 V FA-SVC  : Cancelling job. JobID: 812057698
08-26 16:57:48.041 23701 25607 V FA      : Recording user engagement, ms: 434601
08-26 16:57:48.042  3834  3834 I NetworkController.WifiSignalController: Change in state to: connected=true,enabled=true,level=1,inetCondition=1,iconGroup=IconGroup(Default Wi-Fi Icons),activityIn=true,activityOut=true,rssi=-74,,ssid="CornerStudio24",isGigaWiFi=false,isAttWifiCall=false
08-26 16:57:48.042 23701 25607 V FA      : Activity paused, time: 2918145818
08-26 16:57:48.045 23701 25607 D FA      : Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=434601, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]
08-26 16:57:48.058 21081 25614 V FA-SVC  : Scheduling upload with GcmTaskService
08-26 16:57:48.059 21081 25614 V FA-SVC  : Scheduling task with Gcm. time: 3141687
08-26 16:57:48.075 23701 23701 V AudioManager: abandonAudioFocus() Request Package = com.eesoft.cardlife
08-26 16:57:48.076 21081 25614 V FA-SVC  : Background event processing time, ms: 115
08-26 16:57:48.076  3280 13011 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10291/23701 clientId=android.media.AudioManagerEx@c4845b7versioned.host.exp.exponent.modules.api.av.AVModule@28da124
08-26 16:57:48.084  3280 22483 D LocationManagerService: getProviders()=[passive, gps, network]
08-26 16:57:48.085  3280 10108 D LocationManagerService: getLastLocation: Request[POWER_NONE passive fastest=0 num=1]
08-26 16:57:48.086  3280  4183 D ActivityManager: setTaskToReturnTo : TaskRecord{32896a #2457 A=com.eesoft.cardlife U=0 StackId=1 sz=1} / mTaskToReturnTo = 1
08-26 16:57:48.087  3280 15892 D LocationManagerService: getLastLocation: Request[ACCURACY_FINE gps requested=0 fastest=0 num=1]
08-26 16:57:48.088  3280  4165 D LocationManagerService: getLastLocation: Request[POWER_LOW network requested=0 fastest=0 num=1]
08-26 16:57:48.088  8682  8682 D PenService: [mActivityTriggerHandler] com.eesoft.cardlife/host.exp.exponent.MainActivity
08-26 16:57:48.088  4087  4265 D LGPowerHintPolicy: [Perf] releasePowerHinInfo : release target  com.lge.systemservice.service.LGPowerHintPolicy$PowerHintInfo@5057970
08-26 16:57:48.091 21081 25614 V FA-SVC  : Logging event: origin=fcm,name=notification_foreground(_nf),params=Bundle[{firebase_event_origin(_o)=fcm, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]
08-26 16:57:48.097 21081 25614 V FA-SVC  : Saving event, name, data size: notification_foreground(_nf), 52
08-26 16:57:48.097 21081 25614 V FA-SVC  : Event recorded: Event{appId='com.eesoft.cardlife', name='notification_foreground(_nf)', params=Bundle[{firebase_event_origin(_o)=fcm, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]}
08-26 16:57:48.104 21081 25614 V FA-SVC  : Upload scheduled in approximately ms: 3141594
08-26 16:57:48.139  3280  4183 I WindowManager: Starting window displayed
08-26 16:57:48.149 21081 25614 V FA-SVC  : Cancelling job. JobID: 812057698
08-26 16:57:48.151  3280 15892 V OverlayManager: getOverlayInfosForTarget for user#0
08-26 16:57:48.162 23701 23701 V FA      : onActivityCreated
08-26 16:57:48.167 21081 25618 I EventLogChimeraService: Opted in for usage reporting
08-26 16:57:48.167 21081 25618 I EventLogChimeraService: Aggregate from 1535315491430 (log), 1535315491430 (data)
08-26 16:57:48.174 21081 25614 V FA-SVC  : Scheduling upload with GcmTaskService
08-26 16:57:48.174 21081 25614 V FA-SVC  : Scheduling task with Gcm. time: 3141594
08-26 16:57:48.179 23701 23701 W a       : Could not find listener for key: openOptimisticExperienceActivity
08-26 16:57:48.179 23701 23701 W a       : Could not find listener for key: openExperienceActivity
08-26 16:57:48.182 21081 25614 V FA-SVC  : Background event processing time, ms: 91
08-26 16:57:48.208 23701 25607 V FA      : Activity resumed, time: 2918145984
08-26 16:57:48.211  2638  3542 V Netd    : unexpected event from subsystem cpu
08-26 16:57:48.216 21081 25614 V FA-SVC  : Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=434601, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]
08-26 16:57:48.219 23701 25607 D FA      : Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=-5749745602265750420, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750419}]
08-26 16:57:48.236 21081 25614 V FA-SVC  : Saving event, name, data size: user_engagement(_e), 69
08-26 16:57:48.236 21081 25614 V FA-SVC  : Event recorded: Event{appId='com.eesoft.cardlife', name='user_engagement(_e)', params=Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=434601, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750420}]}
08-26 16:57:48.243  2638  3542 V Netd    : unexpected event from subsystem cpu
08-26 16:57:48.246 21081 25614 V FA-SVC  : Upload scheduled in approximately ms: 3141452
08-26 16:57:48.254  3834  3834 I SystemServicesProxy: RecentApps has 1 item(s).
08-26 16:57:48.255 21081 25614 V FA-SVC  : Cancelling job. JobID: 812057698
08-26 16:57:48.261 23701 25626 W a       : Could not find listener for key: devicePushToken
08-26 16:57:48.265 23701 25626 I b       : gcm Registration Token: f1RuQozNzSw:APA91bE1y9WrTGbrn1TB6LG1Oj1Q7FL-YAU3UC61971V2QvMLq8Uoy6nUZR0gcss0pXz5qtHORLzv3k_5aFLSed1SqsS6TFtWFSs_DC9cxLpabAa0tAkKEU0heNiA07olhmnxJDb1BWG
08-26 16:57:48.274 21081 25614 V FA-SVC  : Scheduling upload with GcmTaskService
08-26 16:57:48.274 21081 25614 V FA-SVC  : Scheduling task with Gcm. time: 3141452
08-26 16:57:48.275  3280  3629 D LocationManagerService: getProviders()=[passive, gps, network]
08-26 16:57:48.277  3280  4172 D LocationManagerService: getLastLocation: Request[POWER_NONE passive fastest=0 num=1]
08-26 16:57:48.278  3280 10107 D LocationManagerService: getLastLocation: Request[ACCURACY_FINE gps requested=0 fastest=0 num=1]
08-26 16:57:48.279  2623  2657 I PowerRM : System FW:0 SO:0 GT:0 CAPP:-1 APP:0
08-26 16:57:48.280  3280 15892 D LocationManagerService: getLastLocation: Request[POWER_LOW network requested=0 fastest=0 num=1]
08-26 16:57:48.282 21081 25614 V FA-SVC  : Background event processing time, ms: 66
08-26 16:57:48.283  3280  4165 D InputDispatcher: Focus entered window: Window{10ff835 u0 com.eesoft.cardlife/host.exp.exponent.MainActivity}
08-26 16:57:48.286  2623 25629 I Thermal-Lib: Thermal-Lib-Client: Client request sent
08-26 16:57:48.286  2620  2713 I ThermalEngine: Thermal-Server: Thermal received msg from  prm
08-26 16:57:48.286  2620  2713 E ThermalEngine: ========= Youtube Mode :0 ==============
08-26 16:57:48.296 21081 25614 V FA-SVC  : Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=-5749745602265750420, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750419}]
08-26 16:57:48.307 21081 25614 V FA-SVC  : Saving event, name, data size: screen_view(_vs), 97
08-26 16:57:48.307 21081 25614 V FA-SVC  : Event recorded: Event{appId='com.eesoft.cardlife', name='screen_view(_vs)', params=Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=-5749745602265750420, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5749745602265750419}]}
08-26 16:57:48.312 21081 25614 V FA-SVC  : Upload scheduled in approximately ms: 3141386
08-26 16:57:48.313 21081 25614 V FA-SVC  : Cancelling job. JobID: 812057698
08-26 16:57:48.326 21081 25614 V FA-SVC  : Scheduling upload with GcmTaskService
08-26 16:57:48.326 21081 25614 V FA-SVC  : Scheduling task with Gcm. time: 3141386
08-26 16:57:48.334 21081 25614 V FA-SVC  : Background event processing time, ms: 38
08-26 16:57:48.376 23701 23701 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-26 16:57:48.377 23701 23701 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-26 16:57:48.377 23701 23701 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@d0b9122 time:1080226208
08-26 16:57:48.378  4087 11592 W LGPowerHintPolicy: [Perf] setPowerHintBoostCancelIfNeeded : send boost cancel msg after 500ms
08-26 16:57:48.380  4087  4262 W LGPowerHintAppInfoPolicy: [Perf] handleAppInfo : tunermode = 0 / isGame = 0 / fps= -1 / ofValue= -1
08-26 16:57:48.389  3280  3348 I ActivityManager: Displayed com.eesoft.cardlife/host.exp.exponent.MainActivity: +301ms
```

**Comment by KthProg** [comment]
I fixed this. The problem was my fix for another issue. For anyone who detached this from Expo, and had this issue (https://github.com/zo0r/react-native-push-notification/issues/432), and copied the solution: in order to get the current instance of the react instance manager, you need to write it like this instead:
```
package host.exp.exponent;


import android.app.Activity;
import android.util.Log;

import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

import expolib_v1.okhttp3.OkHttpClient;
import host.exp.expoview.Exponent;

// Needed for `react-native link`
// import com.facebook.react.ReactApplication;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.reactnativepayments.ReactNativePaymentsPackage;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactInstanceManager;

public class MainApplication extends ExpoApplication implements ReactApplication {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        // new MainReactPackage(),
        new ReactNativePushNotificationPackage(),
        new ReactNativePaymentsPackage()
    );
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    public ReactInstanceManager getReactInstanceManager(){
      Log.d("ReactNativeHost", "Fetching manager from Exponent (override)");
      Activity activity = Exponent.getInstance().getCurrentActivity();
      if(activity instanceof MainActivity){
        return ((MainActivity)activity).getReactInstanceManager();
      }
      Log.d("ReactNativeHost", "Activity was not main activity");
      return null;
    }

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new ReactNativePushNotificationPackage(),
        new ReactNativePaymentsPackage()
      );
    }
  };

  @Override
  public String gcmSenderId() {
    return getString(R.string.gcm_defaultSenderId);
  }

  @Override
  public boolean shouldUseInternetKernel() {
    return BuildVariantConstants.USE_INTERNET_KERNEL;
  }

  public static OkHttpClient.Builder okHttpClientBuilder(OkHttpClient.Builder builder) {
    // Customize/override OkHttp client here
    return builder;
  }
}

```

and update your main activity like so:
```
package host.exp.exponent;

import android.content.Intent;
import android.os.Bundle;

import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactPackage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import abi23_0_0.com.facebook.react.ReactActivity;
import host.exp.exponent.generated.DetachBuildConstants;
import host.exp.exponent.experience.DetachActivity;

public class MainActivity extends DetachActivity {

  @Override
  public String publishedUrl() {
    return "exp://exp.host/@kthprog/2e-card-life";
  }

  @Override
  public String developmentUrl() {
    return DetachBuildConstants.DEVELOPMENT_URL;
  }

  @Override
  public List<String> sdkVersions() {
    return new ArrayList<>(Arrays.asList("27.0.0"));
  }

  @Override
  public List<ReactPackage> reactPackages() {
    return ((MainApplication) getApplication()).getPackages();
  }

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @Override
  public Bundle initialProps(Bundle expBundle) {
    // Add extra initialProps here
    return expBundle;
  }

    public ReactInstanceManager getReactInstanceManager(){
      return ((ReactInstanceManager)(Object)mReactInstanceManager.get());
    }

  @Override
  public void onActivityResult(int requestCode, int resultCode, Intent data) {
    getReactInstanceManager().onActivityResult(this, requestCode, resultCode, data );
  }
}

```

**Comment by KthProg** [comment]
As far as this repo goes, it needs to be updated to work with applications detached from Expo.
