### ISSUE TITLE
com.google.firebase.iid.zzf cannot be cast to com.google.android.gms.iid.zzi

### ISSUE THREAD

**Issue by binonxia** [zo0r/react-native-push-notification#882]
1. use the library version 3.1.1
2. the app crash when the android receive a remote notification, but it's no problem in the ios
3. all the error:

> java.lang.ClassCastException: com.google.firebase.iid.zzf cannot be cast to com.google.android.gms.iid.zzi
        at com.google.android.gms.iid.zzk.onServiceConnected(Unknown Source:4)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1658)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1687)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

4. build.gradle

> googlePlayServicesVersion = "+" // default: "+"
    firebaseVersion ="+"
    compileSdkVersion = 27 // default: 23
    buildToolsVersion = '27.0.3' // default: "25.0.2"
    targetSdkVersion = 27 // default: 22
    supportLibVersion = "27.0.1"

**Comment by opolyo01** [comment]
I removed supportLibVersion = "27.0.1" from ext, and also make sure your app/build.gradle has the same #s with a root gradle.  I am only day 2 on this project, so also discovering things along the way.  I am on RN 44.

**Comment by kevupton** [comment]
This works:
https://github.com/zo0r/react-native-push-notification/issues/796#issuecomment-410801969

My problem was using FCM, (I setup for GCM, and my manifest was wrong).

**Comment by nartjie101** [comment]
If you are using GCM, please make sure that you are using RNPushNotificationListenerServiceGcm in:

`<service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>`

Not RNPushNotificationListenerService, that was used on previous versions.
