### ISSUE TITLE
Error local push notification or foreground notification

### ISSUE THREAD

**Issue by gifary** [zo0r/react-native-push-notification#891]
Exception in native call
                                                                             java.lang.RuntimeException: Could not invoke RNPushNotification.presentLocalNotification
                                                                                 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
                                                                                 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
                                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                                 at java.lang.Thread.run(Thread.java:764)
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
                                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:789) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
                                                                                 at android.os.Looper.loop(Looper.java:164) 
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
                                                                                 at java.lang.Thread.run(Thread.java:764) 
                                                                              Caused by: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.hellobeauty.vendor-Ewin2vBQvqGfziszebiGMA==/base.apk:classes2.dex)
                                                                                 at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendToNotificationCentre(RNPushNotificationHelper.java:165)
                                                                                 at com.dieam.reactnativepushnotification.modules.RNPushNotification.presentLocalNotification(RNPushNotification.java:140)
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
                                                                                 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
                                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:789) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
                                                                                 at android.os.Looper.loop(Looper.java:164) 
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
                                                                                 at java.lang.Thread.run(Thread.java:764)

**Comment by Gp2mv3** [comment]
Check your link.

(And try to format a bit your questions when opening an issue)
