### ISSUE TITLE
App crash on startup on Android - 7.1.1, 8, 9

### ISSUE THREAD

**Issue by CarstenHoyer** [zo0r/react-native-push-notification#927]
Steps to reproduce:
In a typeScript enabled project:
`yarn add react-native-push-notification && yarn add @types/react-native-push-notification`
`react-native run-android`

What will happen:
The app will crash twice and then give a message like "The app keeps crashing".

I don't think I get any log messages to work with.

Device: Motorola Moto(G6) (Android 8.0.0, API 26)

react-native info
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.11.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
```

**Comment by Vincenzo1997** [comment]
I have the same issue :((

**Comment by CarstenHoyer** [comment]
This issue was unrelated to react-native-push-notification and I am closing the issue. It turned out that I _did_ get an error in logcat, and that the issue was related to google maps.

The solution was here https://github.com/react-community/react-native-maps/issues/818#issuecomment-288567562

```
10-31 14:06:18.328 4941-5027/dk.dac.app E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: dk.dac.app, PID: 4941
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
        at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:768)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:175)
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:55)
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:132)
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:129)
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54) 
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
        at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:768) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:175) 
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:55) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:132) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:129) 
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54) 
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
        at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:768) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:175) 
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:55) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:132) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:129) 
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/dk.dac.app-Up_FRyI3SbZzlgv3ptaTIA==/base.apk"],nativeLibraryDirectories=[/data/app/dk.dac.app-Up_FRyI3SbZzlgv3ptaTIA==/lib/x86, /data/app/dk.dac.app-Up_FRyI3SbZzlgv3ptaTIA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54) 
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
        at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:768) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:175) 
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:55) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:132) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:129) 
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by CarstenHoyer** [comment]
It is related to #682,  and I think the solution is this: https://github.com/zo0r/react-native-push-notification/issues/682#issuecomment-375196275

**Comment by Vincenzo1997** [comment]
I did what is wrote in  #682 (comment) but that doesn't fix the problem

**Comment by Vincenzo1997** [comment]
And also I have google maps in my project

**Comment by CarstenHoyer** [comment]
@Vincenzo1997 - could you open a new issue and reference this?

**Comment by gSrujana26** [comment]
App crashes when Pushnotification.configure called
